# Generated by Django 3.2.6 on 2021-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='permissions',
            field=models.PositiveSmallIntegerField(default=493),
        ),
    ]
