# Generated by Django 3.2.6 on 2021-08-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0002_fileversion_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='efile',
            field=models.FileField(blank=True, null=True, upload_to='sync/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='uhash',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
