# Generated by Django 3.2.6 on 2021-08-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0003_auto_20210815_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nstore.synckey')),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('created', 'key')},
            },
        ),
        migrations.AddField(
            model_name='fileversion',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nstore.filetransaction'),
            preserve_default=False,
        ),
    ]
