# Generated by Django 3.2.6 on 2021-08-27 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0004_auto_20210815_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
