# Generated by Django 3.2.7 on 2021-10-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0005_fileversion_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='uhash',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
    ]
