# Generated by Django 3.2.8 on 2021-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0006_alter_fileversion_uhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='uhash',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
