# Generated by Django 3.2.6 on 2021-08-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstore', '0002_alter_fileversion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='syncfile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='synckey',
            options={'ordering': ('-created',)},
        ),
    ]
